title: Homelab
description: Media & automation
theme: dark
color: slate

target: _blank

headerStyle: boxed
iconStyle: theme
statusStyle: dot

language: en-GB

layout:
  Media:
    tab: Home
    style: column
    columns: 4

  Automation:
    tab: Home
    style: column
    columns: 4

  Downloading:
    tab: Home
    style: column
    columns: 3

  Monitoring:
    tab: Home
    style: column
    columns: 3

  Personal:
    tab: Personal
    style: row
    columns: 3
